# -*- coding: utf-8 -*-
"""Sadrzaj stranice Usluge i pod-stranica. Copy je izveden iz context.md:
karakteristika -> naslov, korist -> opis, dokaz sa terena -> reference.

Nista ovdje nije izmisljeno. Gdje klijent nije dao podatak (avans, rok po
tipu posla), tekst ga ne pominje umjesto da nagadja.

`stranica: False` znaci da usluga ostaje samo stavka u listi, bez svoje
pod-stranice. Za kontejnere je tako jer imamo jednu jedinu fotografiju.
"""

USLUGE = [
{
 'slug': 'metalne-konstrukcije',
 'stranica': True,
 'naslov': 'Nosive metalne konstrukcije',
 'naslov_hero': 'Nosive metalne<br>konstrukcije',
 'kratko': 'Krovne, međuspratne i platforme. Veliki otvoren prostor bez stubova nasred prostorije, brža gradnja nego betonom i manje opterećenje na objekat.',
 'slika': 'assets/img/rad-04-detalj-spoja.jpg',
 'alt': 'Krovna metalna konstrukcija sa rešetkastim nosačima, Caffe Porta',
 'slika_hero': 'assets/img/rad-04-detalj-spoja.jpg',
 'obim': ['Krovne i međuspratne konstrukcije',
          'Platforme i rešetkasti nosači',
          'Hale i nadstrešnice',
          'Izrada po projektu',
          'Antikorozivna zaštita pre isporuke'],
 'uvod_naslov': 'Metal nosi ono što zid ne može',
 'uvod': ['Kad prostor treba da ostane otvoren, konstrukcija ide u metal. Nema stubova nasred sale, raspon je veći, a objekat nosi manje težine nego sa betonskom pločom.',
          'Radimo po projektu, sa vašim projektantom ili sa saradnikom na koga vas uputimo. Izrada ide u radionici na Avalskoj, pa je vreme na objektu kratko.'],
 'blokovi': [
   ('Krovne konstrukcije', 'Rešetkasti nosači i krovni skelet za ugostiteljske i poslovne objekte.',
    'Krovna konstrukcija Caffe Porta, Kragujevac.'),
   ('Međuspratne i platforme', 'Konstrukcija platforme sa gotovom podnom oblogom, kad je potrebno dobiti sprat u postojećoj visini.',
    'Platforma sa daskom 50 mm i azmofonom, MATIS New Point.'),
   ('Hale i nadstrešnice', 'Pokriven prostor za robu, mašine ili vozila, brzo i bez klasične gradnje.',
    'Iz ponude profila.'),
   ('Antikorozivna zaštita', 'Priprema površine, pocinkovanje ili plastifikacija i završni nanosi, pre nego što konstrukcija dođe na objekat.',
    'Garancija na zaštitu dve godine.'),
 ],
},
{
 'slug': 'kapije-i-ograde',
 'stranica': True,
 'naslov': 'Kapije i ograde',
 'naslov_hero': 'Kapije<br>i ograde',
 'kratko': 'Ulaz koji radi svaki dan bez zapinjanja i granica placa koja izgleda završeno, a ne improvizovano. Klizne i krilne kapije, panelne, dvorišne i industrijske ograde.',
 'slika': 'assets/img/rad-01-celicna-hala.jpg',
 'alt': 'Dekorativna klizna kapija DOSTOJNA u Kutlovu, izrađena sa Simetra d.o.o.',
 'slika_hero': 'assets/img/rad-06-nadstresnica-garaza.jpg',
 'obim': ['Klizne i krilne kapije',
          '3D panelne ograde',
          'Dvorišne i industrijske ograde',
          'Balkonski gelenderi i dekorativne ograde',
          'Pocinkovanje i plastifikacija'],
 'uvod_naslov': 'Prvi utisak o kući i o firmi',
 'uvod': ['Kapija se otvara svaki dan, po kiši i po mrazu. Zato se razlika između dobre i loše ne vidi na montaži nego kroz dve zime, na vođici, šarki i na mestu gde je zaštita popustila.',
          'Radimo od tipske panelne ograde do kapije koja je sama po sebi znak firme. Merimo na licu mesta, jer se otvor i pad terena ne pogađaju iz kataloga.'],
 'blokovi': [
   ('Klizne kapije', 'Za dvorišta i poslovne ulaze, sa vođicom i nosačima dimenzionisanim prema širini otvora i nagibu terena.',
    'Klizne kapije i 3D paneli, Ford salon.'),
   ('Dekorativne kapije', 'Puno lice sa izrađenim znakom, kad kapija treba da radi i kao obeležje objekta.',
    'Kapija „DOSTOJNA", Kutlovo, u saradnji sa Simetra d.o.o.'),
   ('Ograde i gelenderi', 'Panelne, dvorišne, industrijske i balkonske, sa oblaganjem kompakt pločama kad fasada to traži.',
    'Ograda obložena kompaktom, Blazeks MV, Aerodrom.'),
   ('Zaštita koja traje', 'Pocinkovano i farbano sa svim nanosima. Ograda bez pripreme i cinka počne da rđa kroz dve zime i onda se plaća dvaput.',
    'Garancija na zaštitu dve godine.'),
 ],
},
{
 'slug': 'stepenista',
 'stranica': True,
 'naslov': 'Stepeništa i protivpožarna stepeništa',
 'naslov_hero': 'Stepeništa i PP<br>stepeništa',
 'kratko': 'Bezbedan i miran hod, stepenište koje ne peva i ne klizi. Protivpožarno stepenište je uslov za pregled i upotrebnu dozvolu.',
 'slika': 'assets/img/hero-radnici-zalazak.jpg',
 'alt': 'Spoljna protivpožarna metalna stepeništa na fasadi objekta Ženeva Lux',
 'slika_hero': 'assets/img/hero-radnici-zalazak.jpg',
 'obim': ['Unutrašnja i spoljna stepeništa',
          'Protivpožarna (evakuaciona) stepeništa',
          'Gazišta i gelenderi',
          'Izrada po projektu',
          'Montaža sopstvenom ekipom'],
 'uvod_naslov': 'Posao sa projektom i sa odgovornošću',
 'uvod': ['Stepenište je jedini deo objekta po kome svi hodaju svaki dan. Ako pod nogom radi ili gazište klizi, to se ne popravlja farbanjem.',
          'Protivpožarna stepeništa su zaseban posao: rade se po projektu, prolaze pregled i bez njih objekat ne dobija upotrebnu dozvolu. To nas odvaja od radionica koje rade samo tipske ograde.'],
 'blokovi': [
   ('Protivpožarna stepeništa', 'Spoljna evakuaciona stepeništa sa podestima i gelenderima, po projektu i pod pregledom.',
    'Metalna PP stepeništa, objekat Ženeva Lux.'),
   ('Unutrašnja stepeništa', 'Nosač, gazišta i gelender uklopljeni u enterijer, sa obradom koja ne odaje da je konstrukcija metalna.',
    'Stepenište za BLAŽEKS nameštaj, Sušica.'),
   ('Spoljna stepeništa', 'Prilazi i pomoćni ulazi na stambenim i poslovnim objektima, sa zaštitom računatom na spoljne uslove.',
    'Više objekata u Kragujevcu.'),
   ('Gazišta i gelenderi', 'Dorada i zamena na postojećim stepeništima, kad je nosač dobar a hod nije.',
    'Radi se i kao samostalan posao.'),
 ],
},
{
 'slug': 'letnje-baste',
 'stranica': True,
 'naslov': 'Letnje i zatvorene bašte',
 'naslov_hero': 'Letnje i zatvorene<br>bašte',
 'kratko': 'Više stolova i gost koji sedi po kiši i zimi. Bašta se vraća kroz jednu sezonu, ne kroz godine.',
 'slika': 'assets/img/rad-05-montaza-na-terenu.jpg',
 'alt': 'Zatvorena bašta sa drvenom tavanicom na metalnoj konstrukciji, Mileva Koncept, Grivac',
 'slika_hero': 'assets/img/rad-05-montaza-na-terenu.jpg',
 'obim': ['Letnje i zatvorene bašte',
          'Pergole, krov i zastakljenje',
          'Drvena obloga i tavanica',
          'Deking na metalnoj podkonstrukciji',
          'Gotovo pre sezone'],
 'uvod_naslov': 'Prostor koji radi dvanaest meseci',
 'uvod': ['Ugostitelju bašta nije ukras nego stolovi. Otvorena radi četiri meseca, zastakljena i pokrivena radi celu godinu, a razlika se vidi na prvom kišnom vikendu.',
          'Znamo šta znači „mora da bude gotovo pre sezone" i planiramo posao oko tog datuma. Zato se bašte ugovaraju zimi. Ako je kasno, reći ćemo iskreno šta stižemo, a šta ne.'],
 'blokovi': [
   ('Zatvorene bašte', 'Metalna konstrukcija, zastakljenje i drvena tavanica, za rad tokom cele godine.',
    'Zatvorena bašta, restoran Mileva Koncept, Grivac.'),
   ('Letnje bašte i pergole', 'Konstrukcija, krov i drvena obloga za terase i ulične bašte.',
    'Kafana Paligorić i „Stara Srbija", Kragujevac.'),
   ('Deking', 'Drvena terasa na metalnoj podkonstrukciji. Ostaje ravna i posle zima, ne uleže i ne krivi se kao na drvenoj podlozi.',
    'Deking uz bazen, Kosmaj.'),
   ('Rad bez zatvaranja lokala', 'Većina posla se odradi u radionici. Na objekat izlazimo sa gotovim elementima, radimo van radnog vremena kad je moguće i za sobom čistimo.',
    'Dogovara se pre početka.'),
 ],
},
{
 'slug': 'deking-i-enterijer',
 'stranica': True,
 'naslov': 'Enterijer i završna obrada',
 'naslov_hero': 'Enterijer i<br>završna obrada',
 'kratko': 'Metal nosi, a drvo, staklo i kompakt ploče daju izgled. Lokal dobija prepoznatljiv karakter, sve po meri prostora, ne iz kataloga.',
 'slika': 'assets/img/rad-poslovna-hala.jpg',
 'alt': 'Enterijer lokala Čudesa u Kragujevcu, šank i metalna konstrukcija po meri prostora',
 'slika_hero': 'assets/img/rad-poslovna-hala.jpg',
 'obim': ['Šankovi, stolovi i police',
          'Staklene pregrade',
          'Ukrasne maske za klima uređaje',
          'Oblaganje kompakt pločama',
          'Dekorativni metalni detalji'],
 'uvod_naslov': 'Detalj po kome se lokal pamti',
 'uvod': ['Enterijer je jedini deo posla koji gost stvarno gleda izbliza. Šank, pregrada i polica po meri prostora rade ono što nameštaj iz kataloga ne može.',
          'Retko radimo samo metal. Metal nosi, a drvo, staklo i kompakt daju izgled, i kombinacija je i jača i lepša od bilo čega samostalno.'],
 'blokovi': [
   ('Šankovi i enterijerske konstrukcije', 'Nosive i vidljive konstrukcije za ugostiteljske lokale, izrađene prema merama prostora.',
    'Lokal „Čudesa", Kragujevac.'),
   ('Staklene pregrade', 'Podela prostora bez zidanja, sa metalnim okvirom koji ostaje vidljiv kao deo enterijera.',
    'Radi se uz enterijerske konstrukcije.'),
   ('Maske za klima uređaje', 'Instalacije nestaju sa fasade i objekat izgleda dovršeno.',
    'Ukrasne maske, objekat „Orbita života".'),
   ('Oblaganje kompaktom', 'Završna obloga na ogradama i konstrukcijama, kad fasada traži ravnu površinu bez vidljivog profila.',
    'Ograda Blazeks MV, Aerodrom.'),
 ],
},
{
 'slug': None,
 'stranica': False,
 'naslov': 'Modularni kontejneri',
 'kratko': 'Gotov, useljiv prostor za nedelje umesto meseci. Kad se posao preseli, kontejner ide sa vama. Za razliku od svega ostalog što radimo po meri, ovo je proizvod: poznat rok, poznata izrada.',
 'slika': 'assets/img/rad-hala-kopaonik.jpg',
 'alt': 'Modularni kontejner NP Čelik, stambena izvedba sa prozorima i ulaznim vratima',
 'obim': ['Stambeni', 'Magacinski', 'Građevinski', 'Sanitarni', 'Premeštanje na novu lokaciju'],
},
]
